apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        tier: backend
        role: master
    spec:
      containers:
      - name: hello-world
        image: tomcat:9.0
        ports:
        - containerPort: 8080
